name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up docker compose
      run: docker compose up -d
    - name: reformating
      run: docker exec backend_todo sh -c "black ."
    - name: run tests
      run: docker exec backend_todo sh -c "pytest ."
     
